### ISSUE TITLE
не качает с readmanga

### ISSUE THREAD

**Issue by TristisOris** [MonkAlex/MangaReader#177]
в старом и новом клиентах "главы не найдены".

```
2023-06-03 17:20:29.9463 13556 1 1.51.8.38 Debug Command 'Add' started.
2023-06-03 17:20:29.9763 13556 1 1.51.8.38 Debug LoginCache refresh.
2023-06-03 17:20:31.7069 13556 1 1.51.8.38 Debug Context Show preview for manga from uri https://readmanga.live/yorha___otchet_o_vysadke_na_perl_harbor closed (Elapsed 1,76 seconds)
2023-06-03 17:20:34.8940 13556 1 1.51.8.38 Debug Command 'Subscribe' started.
2023-06-03 17:20:35.9809 13556 15 1.51.8.38 Debug New Readmanga (YoRHa - Pearl Harbor Descent Mission Record).
2023-06-03 17:20:36.0192 13556 15 1.51.8.38 Info Добавлена манга YoRHa - Pearl Harbor Descent Mission Record
2023-06-03 17:20:36.0310 13556 1 1.51.8.38 Debug Context Execute closed (Elapsed 1,13 seconds)
2023-06-03 17:20:57.2184 13556 1 1.51.8.38 Debug Command 'Обновить библиотеку' started.
2023-06-03 17:20:57.2184 13556 1 1.51.8.38 Info Обновление манги
2023-06-03 17:20:57.2308 13556 1 1.51.8.38 Info Обновление YoRHa - Pearl Harbor Descent Mission Record
2023-06-03 17:20:58.0677 13556 15 1.51.8.38 Error Главы не найдены по адресу https://readmanga.live/yorha___otchet_o_vysadke_na_perl_harbor
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Reverse[TSource](IEnumerable`1 source)
   at Grouple.GroupleParser.UpdateContent(IManga manga) in C:\projects\mangareader\Sites\Grouple.ru\GroupleParser.cs:line 177
2023-06-03 17:20:58.0917 13556 15 1.51.8.38 Debug Context Download updates for manga with id 1 closed (Elapsed 0,87 seconds)
2023-06-03 17:20:58.0917 13556 15 1.51.8.38 Info Обновление манги завершено
2023-06-03 17:21:17.1496 13556 1 1.51.8.38 Debug Command 'Открыть папку' started.
2023-06-03 17:21:17.1668 13556 1 1.51.8.38 Info Папка Download\YoRHa - Pearl Harbor Descent Mission Record не найдена
```

еще смущает этот абсолютный путь `C:\projects\mangareader\Sites\Grouple.ru\GroupleParser.cs:line 177`

**Comment by MonkAlex** [comment]
Постараюсь сегодня глянуть. 

Абсолютный путь - просто путь к тому, из чего был собран проект, имеет отношение чисто в машине сборки.

**Comment by MonkAlex** [comment]
https://github.com/MonkAlex/MangaReader/releases/tag/1.51.9.39

Должно работать
